// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package container

import (
	"github.com/friendsofgo/gopherapi/pkg"
	"github.com/friendsofgo/gopherapi/pkg/adding"
	"github.com/friendsofgo/gopherapi/pkg/fetching"
	"github.com/friendsofgo/gopherapi/pkg/modifying"
	"github.com/friendsofgo/gopherapi/pkg/removing"
	"github.com/friendsofgo/gopherapi/pkg/server"
	"github.com/friendsofgo/gopherapi/pkg/storage/inmem"
)

// Injectors from wire.go:

func InitializeServer(gophers map[string]gopher.Gopher) server.Server {
	repository := inmem.NewRepository(gophers)
	service := fetching.NewService(repository)
	addingService := adding.NewService(repository)
	modifyingService := modifying.NewService(repository)
	removingService := removing.NewService(repository)
	serverServer := server.New(service, addingService, modifyingService, removingService)
	return serverServer
}
